import { Injectable } from '@nestjs/common';
import { Browser } from 'playwright';
import { RunnerConfig } from 'kayle';
import { IAccessibilityScanner, ScanOptions } from '../interfaces';
import { Issue } from '../entities/issue.entity';
import { BaseAccessibilityScanner } from './base-accessibility-scanner.service';

/**
 * Axe accessibility scanner implementation using Kayle library.
 * 
 * This service provides comprehensive web accessibility scanning by integrating the
 * Axe accessibility testing engine through the Kayle runner. It performs automated
 * accessibility audits and captures visual context through automated screenshot generation.
 * 
 * Key features:
 * - Automated accessibility scanning using Axe rules
 * - Visual issue documentation with element-specific screenshots
 * - Support for authenticated pages via basic auth and custom headers
 * - Help URLs generated algorithmically via AxeRuleService
 * - Comprehensive error handling and logging for debugging
 * - Integration with Playwright for reliable browser automation
 * 
 * The scanner identifies accessibility issues, with help URLs generated
 * by the AxeRuleService using the Deque University documentation pattern.
 * 
 * @implements {IAccessibilityScanner}
 * @extends {BaseAccessibilityScanner}
 */
@Injectable()
export class AxeAccessibilityScanner extends BaseAccessibilityScanner implements IAccessibilityScanner {
  
  /**
   * Performs comprehensive accessibility scanning of a web page using Axe.
   * 
   * This method orchestrates the complete scanning process including:
   * - Browser context configuration with authentication and headers
   * - Page loading and accessibility rule execution via Kayle with Axe runner
   * - Element-specific screenshot capture for visual issue context
   * - Issue conversion to internal entity format
   * 
   * The scanner runs Axe rules for comprehensive accessibility analysis,
   * identifying violations with help URLs generated by the AxeRuleService.
   * 
   * @param url - The target URL to scan for accessibility issues
   * @param browser - Playwright browser instance for page automation
   * @param options - Optional scan configuration including authentication and headers
   * @returns Promise resolving to partial Issue entities ready for database storage
   * @throws {Error} When page loading, scanning, or screenshot capture fails
   */
  async scan(
    url: string,
    browser: Browser,
    options?: ScanOptions,
  ): Promise<Partial<Issue>[]> {
    this.logger.log(`Starting Axe accessibility scan for URL: ${url}`);

    try {
      // Setup screenshot directory
      const screenshotDir = this.getScreenshotDirectory();
      await this.ensureScreenshotDirectory(screenshotDir);

      // Create browser context and page
      const { context, page } = await this.createBrowserContext(browser, options);

      try {
        // Create base Kayle configuration
        const kayleOptions: RunnerConfig = {
          ...this.createBaseKayleConfig(page, browser, url, options),
          runners: ['axe'], // Use Axe runner
        };

        // Run the accessibility scan
        const results = await this.runKayleScan(kayleOptions, url);

        // Take custom screenshots for each issue
        const issuesWithScreenshots = await this.takeScreenshots(
          page,
          results.issues,
          screenshotDir,
        );

        // Convert results to issue entities with screenshots
        const issues = this.convertKayleIssuesToIssues(issuesWithScreenshots);

        this.logger.log(
          `Axe scan completed. Found ${issues.length} issues for URL: ${url}`,
        );

        return issues;
      } finally {
        // Always close context, even if an error occurs
        await context.close();
      }
    } catch (error) {
      this.logger.error(`Failed to scan URL ${url}:`, error);
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown error';
      throw new Error(`Axe accessibility scan failed: ${errorMessage}`);
    }
  }
}
